# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '^helm|^infra|Makefile$|Dockerfile$|\.sql$|go\.mod$|go\.sum|\.yaml$|\.yml|\.env$'
repos:
  # Go validation hooks
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.6.2
    hooks:
      - id: golangci-lint
        types: [go]
        name: golangci-lint
        language: system
        pass_filenames: false

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        types: [go]
        args: [-w]

      - id: go-mod-tidy
        types: [go]
